// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: estimate.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countNearestMerchants = `-- name: CountNearestMerchants :one
SELECT COUNT(DISTINCT m.id)
FROM merchants m
LEFT JOIN items i ON m.id = i.merchant_id
WHERE
    ($1::uuid = '00000000-0000-0000-0000-000000000000'::uuid OR m.id = $1)
    AND (
        $2::text = ''
        OR m.name ILIKE '%' || $2 || '%'
        OR EXISTS (
            SELECT 1 FROM items i2 
            WHERE i2.merchant_id = m.id 
            AND i2.name ILIKE '%' || $2 || '%'
        )
    )
    AND (
        $3::text = ''
        OR m.merchant_category = $3
    )
`

type CountNearestMerchantsParams struct {
	MerchantID       uuid.UUID `json:"merchant_id"`
	SearchName       string    `json:"search_name"`
	MerchantCategory string    `json:"merchant_category"`
}

func (q *Queries) CountNearestMerchants(ctx context.Context, arg CountNearestMerchantsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNearestMerchants, arg.MerchantID, arg.SearchName, arg.MerchantCategory)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEstimate = `-- name: CreateEstimate :one
INSERT INTO estimates (
    user_id, user_lat, user_lng, total_price, estimated_delivery_time_in_minutes
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, total_price, estimated_delivery_time_in_minutes
`

type CreateEstimateParams struct {
	UserID                         uuid.UUID `json:"user_id"`
	UserLat                        float64   `json:"user_lat"`
	UserLng                        float64   `json:"user_lng"`
	TotalPrice                     int64     `json:"total_price"`
	EstimatedDeliveryTimeInMinutes int       `json:"estimated_delivery_time_in_minutes"`
}

type CreateEstimateRow struct {
	ID                             uuid.UUID `json:"id"`
	TotalPrice                     int64     `json:"total_price"`
	EstimatedDeliveryTimeInMinutes int       `json:"estimated_delivery_time_in_minutes"`
}

func (q *Queries) CreateEstimate(ctx context.Context, arg CreateEstimateParams) (CreateEstimateRow, error) {
	row := q.db.QueryRow(ctx, createEstimate,
		arg.UserID,
		arg.UserLat,
		arg.UserLng,
		arg.TotalPrice,
		arg.EstimatedDeliveryTimeInMinutes,
	)
	var i CreateEstimateRow
	err := row.Scan(&i.ID, &i.TotalPrice, &i.EstimatedDeliveryTimeInMinutes)
	return i, err
}

const createEstimateOrder = `-- name: CreateEstimateOrder :exec
INSERT INTO estimate_orders (
    estimate_id, merchant_id, is_starting_point
) VALUES (
    $1, $2, $3
)
`

type CreateEstimateOrderParams struct {
	EstimateID      uuid.UUID `json:"estimate_id"`
	MerchantID      uuid.UUID `json:"merchant_id"`
	IsStartingPoint bool      `json:"is_starting_point"`
}

func (q *Queries) CreateEstimateOrder(ctx context.Context, arg CreateEstimateOrderParams) error {
	_, err := q.db.Exec(ctx, createEstimateOrder, arg.EstimateID, arg.MerchantID, arg.IsStartingPoint)
	return err
}

const createEstimateOrderItem = `-- name: CreateEstimateOrderItem :exec
INSERT INTO estimate_order_items (
    estimate_order_id, item_id, quantity
) VALUES (
    $1, $2, $3
)
`

type CreateEstimateOrderItemParams struct {
	EstimateOrderID uuid.UUID `json:"estimate_order_id"`
	ItemID          uuid.UUID `json:"item_id"`
	Quantity        int       `json:"quantity"`
}

func (q *Queries) CreateEstimateOrderItem(ctx context.Context, arg CreateEstimateOrderItemParams) error {
	_, err := q.db.Exec(ctx, createEstimateOrderItem, arg.EstimateOrderID, arg.ItemID, arg.Quantity)
	return err
}

const getEstimateById = `-- name: GetEstimateById :one
SELECT id, user_id, user_lat, user_lng, total_price, estimated_delivery_time_in_minutes, created_at
FROM estimates
WHERE id = $1::uuid
`

func (q *Queries) GetEstimateById(ctx context.Context, dollar_1 uuid.UUID) (Estimates, error) {
	row := q.db.QueryRow(ctx, getEstimateById, dollar_1)
	var i Estimates
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserLat,
		&i.UserLng,
		&i.TotalPrice,
		&i.EstimatedDeliveryTimeInMinutes,
		&i.CreatedAt,
	)
	return i, err
}

const getEstimateOrderIds = `-- name: GetEstimateOrderIds :many
SELECT id, merchant_id
FROM estimate_orders
WHERE estimate_id = $1
ORDER BY id
`

type GetEstimateOrderIdsRow struct {
	ID         uuid.UUID `json:"id"`
	MerchantID uuid.UUID `json:"merchant_id"`
}

func (q *Queries) GetEstimateOrderIds(ctx context.Context, estimateID uuid.UUID) ([]GetEstimateOrderIdsRow, error) {
	rows, err := q.db.Query(ctx, getEstimateOrderIds, estimateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEstimateOrderIdsRow{}
	for rows.Next() {
		var i GetEstimateOrderIdsRow
		if err := rows.Scan(&i.ID, &i.MerchantID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemPrice = `-- name: GetItemPrice :one
SELECT price
FROM items
WHERE id = $1::uuid AND merchant_id = $2::uuid
`

type GetItemPriceParams struct {
	ItemID     uuid.UUID `json:"item_id"`
	MerchantID uuid.UUID `json:"merchant_id"`
}

func (q *Queries) GetItemPrice(ctx context.Context, arg GetItemPriceParams) (int64, error) {
	row := q.db.QueryRow(ctx, getItemPrice, arg.ItemID, arg.MerchantID)
	var price int64
	err := row.Scan(&price)
	return price, err
}

const getItemPricesByIDsAndMerchants = `-- name: GetItemPricesByIDsAndMerchants :many
SELECT i.id, i.merchant_id, i.price
FROM items i
JOIN (
    SELECT 
        UNNEST($1::uuid[]) AS item_id,
        UNNEST($2::uuid[]) AS merchant_id
) AS pairs ON i.id = pairs.item_id AND i.merchant_id = pairs.merchant_id
`

type GetItemPricesByIDsAndMerchantsParams struct {
	ItemID     []uuid.UUID `json:"item_id"`
	MerchantID []uuid.UUID `json:"merchant_id"`
}

type GetItemPricesByIDsAndMerchantsRow struct {
	ID         uuid.UUID `json:"id"`
	MerchantID uuid.UUID `json:"merchant_id"`
	Price      int64     `json:"price"`
}

func (q *Queries) GetItemPricesByIDsAndMerchants(ctx context.Context, arg GetItemPricesByIDsAndMerchantsParams) ([]GetItemPricesByIDsAndMerchantsRow, error) {
	rows, err := q.db.Query(ctx, getItemPricesByIDsAndMerchants, arg.ItemID, arg.MerchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetItemPricesByIDsAndMerchantsRow{}
	for rows.Next() {
		var i GetItemPricesByIDsAndMerchantsRow
		if err := rows.Scan(&i.ID, &i.MerchantID, &i.Price); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMerchantLatLong = `-- name: GetMerchantLatLong :one
SELECT id, lat, lng
FROM merchants
WHERE id = $1::uuid
`

type GetMerchantLatLongRow struct {
	ID  uuid.UUID `json:"id"`
	Lat float64   `json:"lat"`
	Lng float64   `json:"lng"`
}

func (q *Queries) GetMerchantLatLong(ctx context.Context, merchantID uuid.UUID) (GetMerchantLatLongRow, error) {
	row := q.db.QueryRow(ctx, getMerchantLatLong, merchantID)
	var i GetMerchantLatLongRow
	err := row.Scan(&i.ID, &i.Lat, &i.Lng)
	return i, err
}

const getMerchantsLatLong = `-- name: GetMerchantsLatLong :many
SELECT id, lat, lng
FROM merchants
WHERE id = ANY($1::uuid[])
`

type GetMerchantsLatLongRow struct {
	ID  uuid.UUID `json:"id"`
	Lat float64   `json:"lat"`
	Lng float64   `json:"lng"`
}

func (q *Queries) GetMerchantsLatLong(ctx context.Context, merchantID []uuid.UUID) ([]GetMerchantsLatLongRow, error) {
	rows, err := q.db.Query(ctx, getMerchantsLatLong, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMerchantsLatLongRow{}
	for rows.Next() {
		var i GetMerchantsLatLongRow
		if err := rows.Scan(&i.ID, &i.Lat, &i.Lng); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNearestMerchant = `-- name: GetNearestMerchant :many
WITH user_location AS (
    SELECT ST_SetSRID(ST_Point($1, $2), 4326)::GEOGRAPHY AS point
),
filtered_merchants AS (
    SELECT DISTINCT m.id, ST_Distance(m.location, ul.point) AS distance_meters
    FROM merchants m
    CROSS JOIN user_location ul
    LEFT JOIN items i ON m.id = i.merchant_id
    WHERE
        ($3::uuid = '00000000-0000-0000-0000-000000000000'::uuid OR m.id = $3)
        AND (
            $4::text = ''
            OR m.name ILIKE '%' || $4 || '%'
            OR EXISTS (
                SELECT 1 FROM items i2 
                WHERE i2.merchant_id = m.id 
                AND i2.name ILIKE '%' || $4 || '%'
            )
        )
        AND (
            $5::text = ''
            OR m.merchant_category = $5
        )
    ORDER BY distance_meters ASC, m.id ASC
    LIMIT $7 OFFSET $6
)
SELECT
    m.id AS merchant_id,
    m.name AS merchant_name,
    m.merchant_category,
    m.image_url AS merchant_image_url,
    m.lat,
    m.lng,
    m.created_at AS merchant_created_at,
    COALESCE(i.id, '00000000-0000-0000-0000-000000000000'::uuid) AS item_id,
    COALESCE(i.name, '') AS item_name,
    COALESCE(i.product_category, '') AS product_category,
    COALESCE(i.price, 0) AS price,
    COALESCE(i.image_url, '') AS item_image_url,
    COALESCE(i.created_at, '1970-01-01 00:00:00'::timestamp) AS item_created_at,
    fm.distance_meters
FROM filtered_merchants fm
JOIN merchants m ON fm.id = m.id
LEFT JOIN items i ON m.id = i.merchant_id
ORDER BY fm.distance_meters ASC, m.id ASC, i.created_at ASC NULLS LAST, i.id ASC
`

type GetNearestMerchantParams struct {
	UserLng          interface{} `json:"user_lng"`
	UserLat          interface{} `json:"user_lat"`
	MerchantID       uuid.UUID   `json:"merchant_id"`
	SearchName       string      `json:"search_name"`
	MerchantCategory string      `json:"merchant_category"`
	OffsetRows       int32       `json:"offset_rows"`
	LimitRows        int32       `json:"limit_rows"`
}

type GetNearestMerchantRow struct {
	MerchantID        uuid.UUID   `json:"merchant_id"`
	MerchantName      string      `json:"merchant_name"`
	MerchantCategory  string      `json:"merchant_category"`
	MerchantImageUrl  string      `json:"merchant_image_url"`
	Lat               float64     `json:"lat"`
	Lng               float64     `json:"lng"`
	MerchantCreatedAt time.Time   `json:"merchant_created_at"`
	ItemID            uuid.UUID   `json:"item_id"`
	ItemName          string      `json:"item_name"`
	ProductCategory   string      `json:"product_category"`
	Price             int64       `json:"price"`
	ItemImageUrl      string      `json:"item_image_url"`
	ItemCreatedAt     time.Time   `json:"item_created_at"`
	DistanceMeters    interface{} `json:"distance_meters"`
}

func (q *Queries) GetNearestMerchant(ctx context.Context, arg GetNearestMerchantParams) ([]GetNearestMerchantRow, error) {
	rows, err := q.db.Query(ctx, getNearestMerchant,
		arg.UserLng,
		arg.UserLat,
		arg.MerchantID,
		arg.SearchName,
		arg.MerchantCategory,
		arg.OffsetRows,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetNearestMerchantRow{}
	for rows.Next() {
		var i GetNearestMerchantRow
		if err := rows.Scan(
			&i.MerchantID,
			&i.MerchantName,
			&i.MerchantCategory,
			&i.MerchantImageUrl,
			&i.Lat,
			&i.Lng,
			&i.MerchantCreatedAt,
			&i.ItemID,
			&i.ItemName,
			&i.ProductCategory,
			&i.Price,
			&i.ItemImageUrl,
			&i.ItemCreatedAt,
			&i.DistanceMeters,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
