// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CheckEmailExistsForRole(ctx context.Context, arg CheckEmailExistsForRoleParams) (bool, error)
	CheckUsernameExists(ctx context.Context, username string) (bool, error)
	CreateItem(ctx context.Context, arg CreateItemParams) (uuid.UUID, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (Users, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	GetUserByUsernameAndRole(ctx context.Context, arg GetUserByUsernameAndRoleParams) (Users, error)
	GetUsersByRole(ctx context.Context, arg GetUsersByRoleParams) ([]GetUsersByRoleRow, error)
	MerchantExists(ctx context.Context, id uuid.UUID) (bool, error)
	VerifyAdminByID(ctx context.Context, id uuid.UUID) (VerifyAdminByIDRow, error)
	VerifyUserByID(ctx context.Context, id uuid.UUID) (VerifyUserByIDRow, error)
}

var _ Querier = (*Queries)(nil)
