// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CheckEmailExistsForRole(ctx context.Context, arg CheckEmailExistsForRoleParams) (bool, error)
	CheckUsernameExists(ctx context.Context, username string) (bool, error)
	CountItemsByMerchant(ctx context.Context, arg CountItemsByMerchantParams) (int64, error)
	CreateEstimate(ctx context.Context, arg CreateEstimateParams) (CreateEstimateRow, error)
	CreateEstimateOrder(ctx context.Context, arg CreateEstimateOrderParams) error
	CreateEstimateOrderItem(ctx context.Context, arg CreateEstimateOrderItemParams) error
	CreateItem(ctx context.Context, arg CreateItemParams) (uuid.UUID, error)
	CreateOrderFromEstimate(ctx context.Context, dollar_1 uuid.UUID) (CreateOrderFromEstimateRow, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error
	CreateOrderMerchant(ctx context.Context, arg CreateOrderMerchantParams) (uuid.UUID, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (Users, error)
	GetEstimateById(ctx context.Context, dollar_1 uuid.UUID) (Estimates, error)
	GetEstimateOrderDetails(ctx context.Context, dollar_1 uuid.UUID) ([]GetEstimateOrderDetailsRow, error)
	GetEstimateOrderIds(ctx context.Context, estimateID uuid.UUID) ([]GetEstimateOrderIdsRow, error)
	GetItemPrice(ctx context.Context, arg GetItemPriceParams) (int64, error)
	GetMerchantLatLong(ctx context.Context, merchantID uuid.UUID) (GetMerchantLatLongRow, error)
	GetOrderById(ctx context.Context, dollar_1 uuid.UUID) (Orders, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	GetUserByUsernameAndRole(ctx context.Context, arg GetUserByUsernameAndRoleParams) (Users, error)
	GetUsersByRole(ctx context.Context, arg GetUsersByRoleParams) ([]GetUsersByRoleRow, error)
	ListItemsByMerchant(ctx context.Context, arg ListItemsByMerchantParams) ([]Items, error)
	MerchantExists(ctx context.Context, id uuid.UUID) (bool, error)
	VerifyAdminByID(ctx context.Context, id uuid.UUID) (VerifyAdminByIDRow, error)
	VerifyUserByID(ctx context.Context, id uuid.UUID) (VerifyUserByIDRow, error)
}

var _ Querier = (*Queries)(nil)
