# docker-compose.yml
services:
  postgres:
    image: postgis/postgis:15-3.4-alpine
    container_name: belimang-postgres
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
      - ./seeds:/seeds:ro
    ports:
      - "${DB_PORT}:5432"
    restart: unless-stopped
    networks:
      - belimang-network
  redis:
    image: redis:7-alpine
    container_name: belimang-redis
    env_file:
      - .env
    ports:
      - "${CACHE_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - belimang-network

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: belimang-app
    env_file: .env
    volumes:
      - .:/app:cached
      - go_modules:/go/pkg/mod
    ports:
      - "${SERVER_PORT:-8080}:8080"
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    networks:
      - belimang-network

volumes:
  postgres_data: # /var/lib/postgresql/data # ← extra space after colon!
  redis_data: # /data
  go_modules:

networks:
  belimang-network:
