services:
  postgres:
    image: postgres:15-alpine
    container_name: belimang-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    restart: unless-stopped
    networks:
      - belimang-network

  redis:
    image: redis:7-alpine
    container_name: belimang-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    networks:
      - belimang-network
  
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: belimang-app
    env_file: .env
    volumes:
      - .:/app:cached
      - go_modules:/go/pkg/mod # Cache go modules, faster rebuild
    ports:
      - "${SERVER_PORT:-8080}:8080"
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    networks:
      - belimang-network

volumes:
  postgres_data:
  redis_data:
  go_modules: # Cache go modules, faster rebuild

networks:
  belimang-network: