services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres # ← file Dockerfile kustommu
    container_name: belimang-postgres
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "${DB_PORT}:5432"
    restart: unless-stopped
    networks:
      - belimang-network

  redis:
    image: redis:7-alpine
    container_name: belimang-redis
    env_file:
      - .env
    ports:
      - "${CACHE_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - belimang-network

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: belimang-app
    env_file:
      - .env
    volumes:
      - .:/app:cached
      - go_modules:/go/pkg/mod
    ports:
      - "${HTTP_PORT:-8080}:8080"
    environment:
      ENV: development
      HTTP_PORT: ${HTTP_PORT}
      DATABASE_URL: ${DATABASE_URL}
      REDIS_ADDR: ${REDIS_ADDR}
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    networks:
      - belimang-network

volumes:
  postgres_data:
  redis_data:
  go_modules:

networks:
  belimang-network:
