FROM postgres:18

# Install h3-pg dari repository resmi PostgreSQL
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        postgresql-18-h3 && \
    rm -rf /var/lib/apt/lists/*

CMD ["postgres"]