apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "belimang.fullname" . }}-initdb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "belimang.labels" . | nindent 4 }}
    app.kubernetes.io/component: initdb
data:
  00-create-database.sql: |-
{{ .Files.Get "files/00-create-database.sql" | nindent 4 }}
  01-extensions.sql: |-
{{ .Files.Get "files/01-extensions.sql" | nindent 4 }}
  02-create-users-table.sql: |-
{{ .Files.Get "files/02-create-users-table.sql" | nindent 4 }}
  03-create-merchants-table.sql: |-
{{ .Files.Get "files/03-create-merchants-table.sql" | nindent 4 }}
  04-create-items-table.sql: |-
{{ .Files.Get "files/04-create-items-table.sql" | nindent 4 }}
  05-create-estimates-table.sql: |-
{{ .Files.Get "files/05-create-estimates-table.sql" | nindent 4 }}
  06-create-orders-table.sql: |-
{{ .Files.Get "files/06-create-orders-table.sql" | nindent 4 }}