apiVersion: v1
kind: Secret
metadata:
  name: {{ include "belimang.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "belimang.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ include "belimang.databaseUrl" . | b64enc }}
  DB_PASSWORD: {{ .Values.secrets.database.password | b64enc }}
  JWT_SECRET_KEY: {{ .Values.secrets.jwt.secretKey | b64enc }}