apiVersion: v1
kind: Service
metadata:
  name: belimang-app-service
  namespace: belimang
  labels:
    app: belimang-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: belimang-app
