apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: belimang
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          args:
            - "redis-server"
            - "--appendonly"
            - "yes"
            - "--appendfsync"
            - "everysec"
            - "--maxmemory"
            - "512mb"
            - "--maxmemory-policy"
            - "allkeys-lru"
            - "--save"
            - "900 1"
            - "--save"
            - "300 10"
            - "--save"
            - "60 10000"
          volumeMounts:
            - name: redis-storage
              mountPath: /data
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 5
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 5
          resources:
            limits:
              cpu: "1"
              memory: "768Mi"
            requests:
              cpu: "500m"
              memory: "256Mi"
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pvc
