apiVersion: v1
kind: Secret
metadata:
  name: belimang-secret
  namespace: belimang
type: Opaque
stringData:
  # Using stringData instead of data to avoid base64 encoding
  # Values will be automatically base64 encoded by Kubernetes
  DB_PASSWORD: "${DB_PASSWORD}"
  JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
  DATABASE_URL: "${DATABASE_URL}"
